# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('director', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('poster', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=80)),
                ('has_review', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('reviewer', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Similar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_movie', to='movies.Movie')),
                ('sim1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_one', to='movies.Movie')),
                ('sim2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_two', to='movies.Movie')),
                ('sim3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_three', to='movies.Movie')),
                ('sim4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_four', to='movies.Movie')),
                ('sim5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_five', to='movies.Movie')),
            ],
        ),
    ]
